import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';

const BASE_URL = `http://${window.location.hostname}:8001`;

@Component({
  selector: 'app-cancer-detection',
  standalone: true,
  imports: [CommonModule],
  template: `
    <section class="page">
      <div class="page-header">
        <h1>Cancer Detection</h1>
        <p>Upload a medical image to run the detection model. Results are for screening purposes only.</p>
      </div>

      <div class="content-grid">
        <!-- Upload card -->
        <div class="card">
          <div
            class="drop-zone"
            [class.drag-over]="isDragging"
            [class.has-file]="previewUrl()"
            (dragover)="onDragOver($event)"
            (dragleave)="isDragging = false"
            (drop)="onDrop($event)"
            (click)="fileInput.click()"
          >
            @if (previewUrl()) {
              <img [src]="previewUrl()" class="preview-img" alt="Selected image" />
              <span class="change-hint">Click or drop to change image</span>
            } @else {
              <div class="drop-prompt">
                <span class="drop-icon">🖼</span>
                <span class="drop-text">Click or drag an image here</span>
                <span class="drop-sub">PNG, JPG, JPEG, TIF</span>
              </div>
            }
          </div>

          <input
            #fileInput
            type="file"
            accept=".png,.jpg,.jpeg,.tif,.tiff"
            style="display:none"
            (change)="onFileSelected($event)"
          />

          @if (selectedFile()) {
            <p class="file-name">{{ selectedFile()!.name }}</p>
          }

          <button
            class="submit-btn"
            [disabled]="!selectedFile() || isLoading()"
            (click)="runAnalysis()"
          >
            @if (isLoading()) {
              <span class="spinner"></span> Analyzing…
            } @else {
              Run Analysis
            }
          </button>
        </div>

        <!-- Results card -->
        <div class="card results-card">
          @if (!result() && !isLoading()) {
            <div class="empty-results">
              <p class="empty-title">Results</p>
              <p class="empty-body">Upload an image and run the analysis to see the model output.</p>
            </div>
          }

          @if (isLoading()) {
            <div class="empty-results">
              <p class="empty-body">Running model inference…</p>
            </div>
          }

          @if (result() && !isLoading()) {
            <div class="result-content">
              <div class="finding-row">
                <span class="finding-badge" [class.detected]="result()!.detected" [class.clear]="!result()!.detected">
                  {{ result()!.detected ? 'Cancer Detected' : 'No Cancer Detected' }}
                </span>
              </div>

              <div class="result-section">
                <p class="section-label">Recommendation</p>
                <p class="section-body">{{ result()!.recommendation }}</p>
              </div>

              <p class="disclaimer">
                This result is generated by an AI model and is intended for preliminary screening only.
                It does not constitute a clinical diagnosis. Always consult a qualified medical professional.
              </p>
            </div>
          }

          @if (errorMsg()) {
            <div class="empty-results">
              <p class="error-text">⚠ {{ errorMsg() }}</p>
            </div>
          }
        </div>
      </div>
    </section>
  `,
  styles: [`
    .page {
      padding: 2rem;
      max-width: 1200px;
      margin: 0 auto;
      font-family: 'DM Sans', sans-serif;
    }

    .page-header {
      margin-bottom: 2rem;
      h1 {
        font-size: 1.5rem;
        font-weight: 600;
        color: var(--text-primary);
        margin: 0 0 0.35rem;
      }
      p {
        font-size: 0.9rem;
        color: var(--text-muted);
        margin: 0;
      }
    }

    .content-grid {
      display: grid;
      grid-template-columns: 400px 1fr;
      gap: 1.5rem;
      align-items: start;
      @media (max-width: 820px) { grid-template-columns: 1fr; }
    }

    .card {
      background: var(--surface-1);
      border: 1px solid var(--border);
      border-radius: var(--radius-lg);
      padding: 1.5rem;
      box-shadow: var(--shadow-card);
      display: flex;
      flex-direction: column;
      gap: 1rem;
    }

    .drop-zone {
      border: 2px dashed var(--border);
      border-radius: var(--radius-md);
      min-height: 200px;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      cursor: pointer;
      transition: border-color 0.15s, background 0.15s;
      overflow: hidden;
      position: relative;

      &:hover, &.drag-over {
        border-color: var(--accent);
        background: rgba(37,99,235,0.03);
      }

      &.has-file {
        border-style: solid;
        min-height: 220px;
      }
    }

    .drop-prompt {
      display: flex;
      flex-direction: column;
      align-items: center;
      gap: 0.4rem;
      padding: 2rem;
    }

    .drop-icon { font-size: 2rem; }

    .drop-text {
      font-size: 0.875rem;
      font-weight: 500;
      color: var(--text-secondary);
    }

    .drop-sub {
      font-size: 0.78rem;
      color: var(--text-muted);
    }

    .preview-img {
      width: 100%;
      height: 220px;
      object-fit: cover;
      display: block;
    }

    .change-hint {
      position: absolute;
      bottom: 0;
      left: 0;
      right: 0;
      background: rgba(0,0,0,0.5);
      color: #fff;
      font-size: 0.75rem;
      text-align: center;
      padding: 0.35rem;
    }

    .file-name {
      font-size: 0.8rem;
      color: var(--text-muted);
      margin: 0;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
    }

    .submit-btn {
      width: 100%;
      padding: 0.72rem;
      background: var(--accent);
      color: #fff;
      border: none;
      border-radius: var(--radius-md);
      font-size: 0.9rem;
      font-weight: 600;
      cursor: pointer;
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 0.5rem;
      transition: background 0.15s, opacity 0.15s;

      &:hover:not(:disabled) { background: var(--accent-dark); }
      &:disabled { opacity: 0.5; cursor: not-allowed; }
    }

    .spinner {
      width: 14px;
      height: 14px;
      border: 2px solid rgba(255,255,255,0.35);
      border-top-color: #fff;
      border-radius: 50%;
      animation: spin 0.7s linear infinite;
    }

    @keyframes spin { to { transform: rotate(360deg); } }

    .results-card { min-height: 200px; }

    .empty-results {
      padding: 2rem 1rem;
      text-align: center;
      display: flex;
      flex-direction: column;
      gap: 0.5rem;
    }

    .empty-title {
      font-weight: 600;
      color: var(--text-secondary);
      font-size: 0.95rem;
      margin: 0;
    }

    .empty-body {
      font-size: 0.85rem;
      color: var(--text-muted);
      margin: 0;
    }

    .result-content {
      display: flex;
      flex-direction: column;
      gap: 1.25rem;
    }

    .finding-row {
      display: flex;
      align-items: center;
    }

    .finding-badge {
      padding: 0.4rem 1rem;
      border-radius: 999px;
      font-size: 0.875rem;
      font-weight: 600;

      &.detected {
        background: rgba(239,68,68,0.1);
        color: #ef4444;
        border: 1px solid rgba(239,68,68,0.25);
      }

      &.clear {
        background: rgba(34,197,94,0.1);
        color: #16a34a;
        border: 1px solid rgba(34,197,94,0.25);
      }
    }

    .result-section {
      border-top: 1px solid var(--border);
      padding-top: 1rem;
      display: flex;
      flex-direction: column;
      gap: 0.4rem;
    }

    .section-label {
      font-size: 0.75rem;
      font-weight: 700;
      letter-spacing: 0.06em;
      text-transform: uppercase;
      color: var(--text-muted);
      margin: 0;
    }

    .section-body {
      font-size: 0.875rem;
      color: var(--text-secondary);
      line-height: 1.6;
      margin: 0;
    }

    .disclaimer {
      font-size: 0.78rem;
      color: var(--text-muted);
      line-height: 1.6;
      border-top: 1px solid var(--border);
      padding-top: 1rem;
      margin: 0;
    }

    .error-text {
      font-size: 0.85rem;
      color: #ef4444;
      margin: 0;
    }
  `]
})
export class CancerDetectionComponent {
  selectedFile = signal<File | null>(null);
  previewUrl = signal<string | null>(null);
  isLoading = signal(false);
  errorMsg = signal('');
  result = signal<{ detected: boolean; recommendation: string } | null>(null);

  isDragging = false;

  onDragOver(e: DragEvent): void {
    e.preventDefault();
    this.isDragging = true;
  }

  onDrop(e: DragEvent): void {
    e.preventDefault();
    this.isDragging = false;
    const file = e.dataTransfer?.files?.[0];
    if (file) this.setFile(file);
  }

  onFileSelected(e: Event): void {
    const file = (e.target as HTMLInputElement).files?.[0];
    if (file) this.setFile(file);
  }

  private setFile(file: File): void {
    this.selectedFile.set(file);
    this.result.set(null);
    this.errorMsg.set('');
    const reader = new FileReader();
    reader.onload = () => this.previewUrl.set(reader.result as string);
    reader.readAsDataURL(file);
  }

  runAnalysis(): void {
    const file = this.selectedFile();
    if (!file || this.isLoading()) return;

    this.isLoading.set(true);
    this.result.set(null);
    this.errorMsg.set('');

    const formData = new FormData();
    formData.append('file', file);

    fetch(`${BASE_URL}/cancer_detection`, { method: 'POST', body: formData })
      .then(res => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.json();
      })
      .then((data: { output: string }) => {
        const detected = data.output === 'Cancer Detected';
        this.result.set({
          detected,
          recommendation: detected
            ? 'The model flagged potential malignancy in this image. Please consult an oncologist or specialist promptly for further evaluation and confirmatory testing.'
            : 'No malignancy was flagged by the model. Continue routine screenings as advised by your healthcare provider.',
        });
      })
      .catch(() => {
        this.errorMsg.set('Could not reach the backend. Please check your connection and try again.');
      })
      .finally(() => {
        this.isLoading.set(false);
      });
  }
}
